### ISSUE TITLE
using readme example

### ISSUE THREAD

**Issue by bowerth** [Karasiq/scalajs-highcharts#1]
Helle -
I have been following the Scala.js tutorial at http://www.scala-js.org/tutorial/basic/
I am now trying to include the scalajs-highcharts example in the TutorialApp.scala, unfortunately without success
Could you provide a more comprehensive example?

**Comment by Karasiq** [comment]
See https://github.com/Karasiq/scalajs-highcharts/tree/master/test
- Chart configuration: https://github.com/Karasiq/scalajs-highcharts/blob/master/test/frontend/src/main/scala/com/highcharts/test/frontend/charts/TestBarChartConfig.scala
- Chart rendering: https://github.com/Karasiq/scalajs-highcharts/blob/master/test/frontend/src/main/scala/com/highcharts/test/frontend/HighchartsTestApp.scala

**Comment by bowerth** [comment]
many thanks for this - could you provide the commands to compile or run this example? I am continuously failing...
UPDATE: figured it's a multi-project build and I need to do a `project scalajs-highcharts-test` after starting sbt and before compile/run
Remark: is there a way to terminate the Akka server? the command at the end of def startup() does not seem to terminate the process

```
    Runtime.getRuntime.addShutdownHook(new Thread(new Runnable {
      override def run(): Unit = {
        Await.result(actorSystem.terminate(), FiniteDuration(5, TimeUnit.MINUTES))
      }
    }))
```

**Comment by Karasiq** [comment]
Enter `sbt scalajs-highcharts-test/run` in console to run, then press `Ctrl+C` to terminate

**Comment by bowerth** [comment]
thank you for the reply - I'm using a simple index.html without bootstrap to test the continuously recompiled JS libraries using ~fastOptJS in /test/frontend
another question: is it possible to combine different series types in the same chart? (e.g. column + spline as in http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/combo/)
I am getting the error "could not find implicit value for parameter" from `mkSeries` in `HighchartsUtils.scala` when trying the following:

```
override val series: SeriesCfg = mkSeries(
    new SeriesColumn {
      override val name: js.UndefOr[String] = "Adam"
      override val data: SeriesCfgData[SeriesColumnData] = js.Array[Double](3, 2, 1)
    },
    new SeriesSpline {
      override val name: js.UndefOr[String] = "Spline"
      override val data: SeriesCfgData[SeriesSplineData] = js.Array[Double](3, 3, 3)
    }
)
```

**Comment by Karasiq** [comment]
``` scala
override val series: SeriesCfg = mkSeries(new SeriesColumn {
    override val name: js.UndefOr[String] = "Adam"
    override val data: SeriesCfgData[SeriesColumnData] = js.Array[Double](3, 2, 1)
  }).addSeries(new SeriesSpline {
    override val name: js.UndefOr[String] = "Spline"
    override val data: SeriesCfgData[SeriesSplineData] = js.Array[Double](3, 3, 3)
  })
```

**Comment by bowerth** [comment]
perfect, many thanks! will keep experimenting...

**Comment by bowerth** [comment]
BTW: do you have an example for a pie chart? the data series specification is slightly different from other types (bar, column, line), e.g. `js.Array[Double]` does not work:

from `SeriesPie.scala`
:   `val data: js.UndefOr[js.Array[CleanJsObject[SeriesPieData] | Double]] = js.undefined`

from `SeriesColumn.scala`
:   `val data: js.UndefOr[js.Array[CleanJsObject[SeriesColumnData] | js.Array[js.Any] | Double]] = js.undefined`

**Comment by bowerth** [comment]
also, how would I define the size of a pie chart? (the type in `SeriesPie.scala` is `js.UndefOr[String | Double]`)

**Comment by Karasiq** [comment]
See commit 2c6742fe4f89cafb27715ee2bdea07d3e8437af1
- [Test3dPieChartConfig.scala](https://github.com/Karasiq/scalajs-highcharts/blob/2c6742fe4f89cafb27715ee2bdea07d3e8437af1/test/frontend/src/main/scala/com/highcharts/test/frontend/charts/Test3dPieChartConfig.scala)

![clipboard](https://cloud.githubusercontent.com/assets/7199719/12490830/81e198ba-c06f-11e5-89fd-20dffda42ea5.png)

**Comment by bowerth** [comment]
looking great - the private `mkData` method allows to have compressed syntax - 
any clue how would I define the size (and center on canvas) of this 3D pie chart? (the type in `SeriesPie.scala` is `js.UndefOr[String | Double]`)

**Comment by Karasiq** [comment]
``` scala
override val size: UndefOr[String | Double] = UndefOr.any2undefOrA("30%")
```

Or

``` scala
override val size: UndefOr[String | Double] = "30%".asInstanceOf[String | Double]
```

Or use [implicit](https://github.com/Karasiq/scalajs-highcharts/blob/a0bf9b9cd75f6d8db0824bc0ce21cd98ecddda82/src/main/scala/com/highcharts/HighchartsImplicits.scala#L10)

<hr/>

Update: a3b9a3f78de26a72010954d1ebd49438a15b807f

**Comment by bowerth** [comment]
many thanks, this worked - I only had to import the pipe operator from scala.js, js.`|`
my last question would be: how can the pie chart be inserted into the column chart? see [combo example](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/combo)
Update: I saw your push with the new combo chart type, many thanks for this!

**Comment by Karasiq** [comment]
See the demo page charts
- [TestCombinationChartConfig.scala](https://github.com/Karasiq/scalajs-highcharts/blob/master/test/frontend/src/main/scala/com/highcharts/test/frontend/charts/TestCombinationChartConfig.scala)
  ![screenshot 2016-01-30 015](https://cloud.githubusercontent.com/assets/7199719/12695912/489a7874-c754-11e5-8613-f239c1df6760.png)
